name: 'gh_action_test'
description: 'お試し'
inputs:
  test-inputs:
    description: "inputsのテストです"
    required: true
    default: "foo"
  file_path:
    description: "復号するファイルのパス"
    required: true
    default: "file.txt.gpg"
outputs:
  test-output:
    description: 'outputsのテストです'
  handle:
    description: "result"
    value: ${{ steps.gpg_decrypt.outputs.handle }}
runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      run: |
        ls -la
    - uses: actions/checkout@v4
      with:
        path: 'gpg_action'
        repository: 'kurari50/gpg_action'
        sparse-checkout: |
          action
    - name: ls
      shell: bash
      run: |
        ls -la
    - name: Generate secret file
      shell: bash
      run: |
        cd action
        sh gpg_action.sh
    - name: Add secret mask
      shell: bash
      run: |
        echo -n '::add-mask::' > rwenojrempewaio.txt
        cat action/secret_text.txt >> rwenojrempewaio.txt
        cat rwenojrempewaio.txt
        rm rwenojrempewaio.txt
    - name: Decrypt secret file
      id: gpg_decrypt
      shell: bash
      run: |
        FILE="${{ inputs.file_path }}"
        SECRET_HANDLE=$(echo "$(cat action/secret_text.txt)" | sudo gpg --batch --passphrase-fd 0 --decrypt "${FILE}")
        echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"
