name: 'gh_action_test'
description: 'お試し'
env:
  TEXT: ${{ secrets.TEXT }}
inputs:
  test-inputs:
    description: "inputsのテストです"
    required: true
    default: "foo"
outputs:
  test-output:
    description: 'outputsのテストです'
runs:
  using: composite
  steps:
    - name: Echo
      shell: bash
      run: echo "test"
    - name: gpg decrypt
      run: |
        echo "${{ env.TEXT }}" | sudo gpg --batch --passphrase-fd 0 --decrypt "file.txt.gpg" 
