name: 'gh_action_test'
description: 'お試し'
inputs:
  test-inputs:
    description: "inputsのテストです"
    required: true
    default: "foo"
outputs:
  test-output:
    description: 'outputsのテストです'
  handle:
    description: "result"
    value: ${{ steps.gpg_decrypt.outputs.handle }}
runs:
  using: composite
  steps:
    - name: Generate secret file
      shell: bash
      run: |
        cd action
        sh gpg_action.sh
    - name: Add secret mask
      shell: bash
      run: |
        echo -n '::add-mask::' > rwenojrempewaio.txt
        cat action/secret_text.txt >> rwenojrempewaio.txt
        cat rwenojrempewaio.txt
        rm rwenojrempewaio.txt
    - name: Decrypt secret file
      id: gpg_decrypt
      shell: bash
      run: |
        SECRET_HANDLE=$(echo "$(cat action/secret_text.txt)" | sudo gpg --batch --passphrase-fd 0 --decrypt "file.txt.gpg")
        echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"
