name: 'gh_action_test'
description: 'お試し'
inputs:
  test-inputs:
    description: "inputsのテストです"
    required: true
    default: "foo"
  file_path:
    description: "復号するファイルのパス"
    required: true
    default: "file.txt.gpg"
outputs:
  test-output:
    description: 'outputsのテストです'
  handle:
    description: "result"
    value: ${{ steps.gpg_decrypt.outputs.handle }}
runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      run: |
        ls -la
    - uses: actions/checkout@v4
      with:
        path: 'gpg_action'
        repository: 'kurari50/gpg_action'
        sparse-checkout: |
          action
    - name: ls
      shell: bash
      run: |
        ls -la
    - name: Generate secret file
      shell: bash
      run: |
        if [ -d gpg_action ]
        then
          cd gpg_action
          ls -la
        fi
        cd action
        ls -la
        sh gpg_action.sh
    - name: Add secret mask
      shell: bash
      run: |
        SECRET_FILE_PATH='action/secret_text.txt'
        TEMP_FILE='rwenojrempewaio.txt'
        if [ -d gpg_action ]
        then
          cd SECRET_FILE_PATH='gpg_action/action/secret_text.txt'
        fi
        echo -n '::add-mask::' > ${TEMP_FILE}
        cat ${SECRET_FILE_PATH} >> ${TEMP_FILE}
        cat ${TEMP_FILE}
        rm ${TEMP_FILE}
    - name: Decrypt secret file
      id: gpg_decrypt
      shell: bash
      run: |
        FILE="${{ inputs.file_path }}"
        SECRET_HANDLE=$(echo "$(cat ${SECRET_FILE_PATH})" | sudo gpg --batch --passphrase-fd 0 --decrypt "${FILE}")
        echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"
