name: 'gh_action_test'
description: 'お試し'
inputs:
  test-inputs:
    description: "inputsのテストです"
    required: true
    default: "foo"
outputs:
  test-output:
    description: 'outputsのテストです'
  handle: ${{ steps.gpg_decrypt.outputs.handle }}
runs:
  using: composite
  steps:
    - name: Add mask
      shell: bash
      run: |
        echo -n '::add-mask::' > cmd.txt
        cat secret_text.txt >> cmd.txt
        cat cmd.txt
        rm cmd.txt
    - name: gpg decrypt
      id: gpg_decrypt
      shell: bash
      run: |
        cat secret_text.txt
        SECRET_HANDLE=$(echo "$(cat secret_text.txt)" | sudo gpg --batch --passphrase-fd 0 --decrypt "file.txt.gpg")
        echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"
